### ISSUE TITLE
Generate an AST document

### ISSUE THREAD

**Issue by oltodo** [jesperhh/qmlfmt#16]
Hi! 

Now that I could generate a `qmlfmt` build with success (mainly through your help on the issue https://github.com/jesperhh/qmlfmt/issues/14) I can see it working on my project and formatting my `.qml` files.

But, according how QtCreator reformat the JavaScript part, I think it looks like particularly inelegant. Except the indentation size there isn't any more available option.

So I was wondering if using Prettier could be a solution to improve that, because it already formats the JavaScript code and does it better than QtCreator. To do that I have to create a new plugin for Prettier and I will need a QML parser. I've supposed I could take advantage of the QtCreator's parser part to generate an AST document. WYT?

**Comment by jesperhh** [comment]
Interesting idea! I don't know the Qt Creator/Prettier source code well enough to say if that is the best way to go about it though.

Another possibility would be to improve the Qt Creator formatter - I am sure they would welcome contributions.

I don't think putting it inside this tool would make sense though, but you are more than welcome to use my tool as a starting point to get something working.

**Comment by jesperhh** [comment]
You are more than welcome to use my tool as a starting point to get something working, but I will close this issue, as it is not something I will pursue as part of this tool.

**Comment by oltodo** [comment]
Hi @jesperhh. Thanks for your recommandation!

I've been starting to develop a new project that able us to generate an AST document from a QML file: https://github.com/oltodo/qml-parser. As you see I used your project as a starting point :-).

I'm not at a C++ developer at all so if you look at it closely you would probably be a bit scary. So if you have some advices to give I would be glad.

**Comment by jesperhh** [comment]
I looked at a few of the new files, and I think it looks good - the only thing I noticed which looks a bit odd is that you use both #pragma once and #ifndef guards in your headers, only one of them should suffice :-)

And then once your design settles, feel free to remove my name/copyright from the files and optionally add attribution in the readme instead (or leave it out if you want).
