### ISSUE TITLE
No version number output

### ISSUE THREAD

**Issue by pylipp** [jesperhh/qmlfmt#17]
This is rather minor... however when I run `qmlfmt -v` I get the output

    qmlfmt

but I'd expect 

    qmlfmt 1.0.71

(since I'm testing with the pre-build binary v1.0.71 from the GitHub release page).

**Comment by jesperhh** [comment]
Thanks for reporting the issue, it sounds like an issue with the continuous integration scripts.

I might postpone the fix until I need to do an update to the  tool itself unless it is very inconvenient to you?

**Comment by pylipp** [comment]
That's totally fine, no worries :)

**Comment by thuyndieu** [comment]
it would be nice if you can provide the version of qtcreator used to format qml too ^^

**Comment by jesperhh** [comment]
Not fixed

**Comment by jesperhh** [comment]
Now prints the following:
PS C:\Users\Jesper\Desktop> .\qmlfmt.exe --version
qmlfmt 1.1.0 based on Qt Creator 4.10.2
