### ISSUE TITLE
Distributing as a standalone tool

### ISSUE THREAD

**Issue by oltodo** [jesperhh/qmlfmt#20]
Hi,

I wonder how this tool could be built and distributed in any platform without requiring a Qt installation (a standalone version).

When I build it on my Mac and try to launch on another Mac I get this error:

```
dyld: Library not loaded: @rpath/QtConcurrent.framework/Versions/5/QtConcurrent
 Referenced from: /path/to/qmlfmt
 Reason: image not found
```

Do you have an idea on how I do that?

Regards.

**Comment by jesperhh** [comment]
It is possible, but I have never tried it, see:
https://doc.qt.io/QtForDeviceCreation/qtee-static-linking.html
It might be tricky to get this to work as most documentation is centered around using QMake, not CMake.
