### ISSUE TITLE
"cannot execute binary file" using prebuilt on macOS

### ISSUE THREAD

**Issue by benwiley4000** [jesperhh/qmlfmt#21]
Thanks for this project!

I tried running the command (using both clang and gcc releases of [v1.0.85](https://github.com/jesperhh/qmlfmt/releases/tag/1.0.85):
```console
/path/to/qmlfmt
# and also:
/path/to/qmlfmt /path/to/file.qml
```

Error message:
```console
-bash: /path/to/qmlfmt: cannot execute binary file
```

I tried `chmod +x` etc, still same issue.

System specs:

```console
$ clang -v
Apple LLVM version 10.0.0 (clang-1000.11.45.2)
Target: x86_64-apple-darwin17.7.0
Thread model: posix
InstalledDir: /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin
$ gcc -v
Configured with: --prefix=/Applications/Xcode.app/Contents/Developer/usr --with-gxx-include-dir=/usr/include/c++/4.2.1
Apple LLVM version 10.0.0 (clang-1000.11.45.2)
Target: x86_64-apple-darwin17.7.0
Thread model: posix
InstalledDir: /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin
$ uname -r
17.7.0
```

![](https://i.imgur.com/zT6jRgO.png)

**Comment by jesperhh** [comment]
Unfortunately there is no build for macOS at the moment, both the clang and the GCC build are for Linux (The clang build was added to verify that it could be built on macOS with clang, but I did not verify myself).

However, pull request #22 adds instruction on how to get this using homebrew, can you try that instead? I don't use macOS so I cannot test it.

**Comment by jesperhh** [comment]
Instruction for running on macOS with homebrew have been added with the merge of PR #22

**Comment by benwiley4000** [comment]
Sorry for not responding earlier! Thanks so much, I'll try it out.
