### ISSUE TITLE
More options for format?

### ISSUE THREAD

**Issue by braineo** [jesperhh/qmlfmt#31]
Seems it is using the formatter in QtCreator?

I think this formatter is not very well handling when to wrap a line and creates deep indent for nested JS functions

Can we add more configurable options aside from indent width? On QtCreator there no configs maybe it is possible though the code?

**Comment by jesperhh** [comment]
Unfortunately, I have not found any extra knobs that can be tweaked, I investigated it a bit when I added the options for indentation.

Your best bet is to request a feature for Qt Creator, then I can uptake it here.

**Comment by braineo** [comment]
I see. Thanks for clarification.
