### ISSUE TITLE
Problem with launching cmake

### ISSUE THREAD

**Issue by eperiana** [jesperhh/qmlfmt#35]
Hi there, I follow the tutorial to install your git project on my computer but when i am in the build folder and I launch : 
`cmake ..`

I got the following error  :
`CMake Error at qmljs/CMakeLists.txt:35 (find_package):
  By not providing "FindQt5Qml.cmake" in CMAKE_MODULE_PATH this project has
  asked CMake to find a package configuration file provided by "Qt5Qml", but
  CMake did not find one.

  Could not find a package configuration file provided by "Qt5Qml" with any
  of the following names:

    Qt5QmlConfig.cmake
    qt5qml-config.cmake

  Add the installation prefix of "Qt5Qml" to CMAKE_PREFIX_PATH or set
  "Qt5Qml_DIR" to a directory containing one of the above files.  If "Qt5Qml"
  provides a separate development package or SDK, be sure it has been
  installed.

-- Configuring incomplete, errors occurred!
See also "/home/etienne/qmlfmt/build/CMakeFiles/CMakeOutput.log".`

Qt version : 5.15.2
Cmake version : 3.16.3
OS : Ubuntu 20.04.2 LTS
 GNOME version : 3.36.8

Could you help me please ?

**Comment by jesperhh** [comment]
Hi,

Not sure what is going wrong, the automated build step does not set up any paths to be able to find Qt.

Have you installed qtdeclarative5-dev?
