### ISSUE TITLE
Binaries

### ISSUE THREAD

**Issue by skyronic** [jesperhh/qmlfmt#36]
This isn't an bug with the tool, but I just wanted to ask if it's possible to publish binaries for all platforms as part of a release! 

I had a bunch of trouble to get it to build on Windows due to issues on my system, but it would be great to have a binary for all platforms if possible. Thank you!

**Comment by jesperhh** [comment]
Hi,

The releases page contains builds for Windows and Linux:
https://github.com/jesperhh/qmlfmt/releases/tag/1.1.2
(The .zip is for windows, gcc/clang are for Linux)

**Comment by skyronic** [comment]
Oh. My bad. I didn't check the release earlier. Thank you!
