### ISSUE TITLE
Difference to qmlformat

### ISSUE THREAD

**Issue by C4rsten** [jesperhh/qmlfmt#39]
I am interested in this project, but the readme does not tell me what it does better than `qmlformat`, the command line tool that ships with Qt.

**Comment by jesperhh** [comment]
I haven't tried `qmlformat`, but it did not exist when I wrote this tool.

This tool uses the reformatting engine from Qt Creator, whereas `qmlformat` appears to use reformatting logic from Qt itself - not sure if they produce the same output.

**Comment by vimpostor** [comment]
> not sure if they produce the same output.

They don't and there are many major differences, e.g. `qmlfmt` prefers no semicolon in QML JS, but `qmlformat` inserts a semicolon.
