### ISSUE TITLE
Properties sorting

### ISSUE THREAD

**Issue by Daguerreo** [jesperhh/qmlfmt#44]
Properties are often ordered by meaning instead of alphabetically, so forcing them with an alphabetical order could be a problem.

Example

```
Rectangle {
    color: "red"
    height: 40
    objectName: "foo"
    width: 100
}
```

Obviously  I'd like to have width and height close and an alphabetical order make more difficult to read a complex file.

Would be reasonable to add an option to disable the alphabetical order while keeping the guidelines suggestion active?

**Comment by jesperhh** [comment]
The formatting engine used by this tool is coming from Qt Creator, so any changes/added features would have to be added there first. Currently Qt Creator only supports limited configuration around whitespace.
