### ISSUE TITLE
import qrc:

### ISSUE THREAD

**Issue by mathben** [jesperhh/qmlfmt#5]
Hi, I got segmentation fault when I try to format qml file with import "qrc:..."

Example, in main.qml

`import "qrc:/test"`

To debug, I run with strace
`strace qmlfmt main.qml`

Output :

> stat("/home/mathben/qml_test/qrc:/test", 0x7fff6fa274b0) = -1 ENOENT (No such file or directory)

**Comment by mathben** [comment]
I think we need to use https://doc-snapshots.qt.io/qtcreator-extending/qmljs-modelmanagerinterface.html to load files.

In .pro, we do

> RESOURCES += qml.qrc

I don't find where to set this variable.

https://doc-snapshots.qt.io/qtcreator-extending/qmljs-document.html
The crash happen with line
`document->parse();`

One solution we can do is temporary hide 

> import "qrc:

I think the error is produce here : https://github.com/danimo/qt-creator/blob/master/src/libs/qmljs/qmljsdocument.cpp#L263

**Comment by jesperhh** [comment]
Hi Mathieu,

Thank you for reporting the issue, I will take a look at it tomorrow. I
assume that the files you are testing work with no issues when reformatting
through Qt Creator?

- Jesper

**Comment by mathben** [comment]
Hi Jesper,
Yes, it works with no issues when reformatting through Qt Creator.

Thanks!

**Comment by mathben** [comment]
It's work, thanks you.
