### ISSUE TITLE
Column and line information not shown

### ISSUE THREAD

**Issue by pylipp** [jesperhh/qmlfmt#8]
I was wonderding whether it's possible to remove that line: https://github.com/jesperhh/qmlfmt/blob/4d4399cac266b5a68970aa4d1a469cca440022cf/qmlfmt.cpp#L81

Given a simple erroneous component file like this

```
// MyItem.qml
import QtQuick 2.7
Item {
```

the command `qmlfmt -e MyItem.qml` does output the error but not the location of the error (`Error: Expected token }`). With the aforementioned line removed, it outputs `Error:3:1: Expected token }` which provides more information and can be parsed (which again helps to use qmlfmt as tool for syntax checking plugin in e.g. vim).

**Comment by jesperhh** [comment]
That sounds like a good idea, I will take a look at it.
