### ISSUE TITLE
Formatting of QML comments

### ISSUE THREAD

**Issue by pylipp** [jesperhh/qmlfmt#9]
Running qmlfmt on this:

```
import QtQuick 2.7

Item {
    /* This is a comment
     * of the component */
}
```

returns 

```
import QtQuick 2.7

Item {
    /* This is a comment
         * of the component */
}
```

It seems like the starting asterisk is interpreted as  multiplication sign which causes an increased indent.

**Comment by jesperhh** [comment]
The application is using the same formatter as Qt Creator - if Qt Creator returns the same thing then there is not much I can do.
However, I am currently basing the tool on an old version of Qt Creator, so maybe this has improved in a later version - I take a look at it.
